### ISSUE TITLE
Requires native gcc compiler to build

### ISSUE THREAD

**Issue by ddevienne** [svent/sift#24] opened 2015-10-07 09:05 UTC
> D:\my\go>go get github.com/svent/sift
> # github.com/svent/sift
> 
> exec: "gcc": executable file not found in %PATH%

Which is not readily available on Windows, and makes building from source unnecessarily difficult, just to count lines. I'd happily trade some runtime for a pure-go build. Perhaps there's a way to do both using build flags? Requiring cygwin or mingw for so little C code seems overkill. Or at least use VS on Windows?

Thank you for considering a pure-go build.

**Comment by svent** [comment] 2015-10-07 22:57
sift supports a pure go build since the beginning and it does use build flags to achieve that, but it seems that the go installation does start the compilation with cgo activated although no compiler is available.

On Windows, the following should work:

```
set CGO_ENABLED=0
go get github.com/svent/sift
```

This issue should be a duplicate of #9.

**Closed as completed by svent** 2015-10-07 22:57 UTC

**Comment by ddevienne** [comment] 2015-10-08 07:30
Thank you. Works great.
