### ISSUE TITLE
Segmentation Fault on Centos 5.6

### ISSUE THREAD

**Issue by dsaputra** [svent/sift#29] opened 2015-10-21 04:21 UTC
Hi I also found it do not working on my production server using CENT OS 5.6, it return Segmentation Fault error.

[root@localhost sift]# ./sift information LICENSE
Segmentation fault

**Comment by svent** [comment] 2015-10-21 21:16
Could you test whether this also happens if you execute `sift -V` or `sift --help`?
This looks like a problem of the go runtime - I will try to reproduce it in the next days.

**Comment by svent** [comment] 2015-10-25 18:28
I could reproduce this, the general problem is the missing support for Go on old RedHat/CentOS versions: http://dave.cheney.net/2013/06/18/how-to-install-go-1-1-on-centos-5
Even a simple "hello world" implemented in go might not run on CentOS 5.x (depending on the kernel version).

This cannot be fixed by changing code in sift, so I guess CentOS 5.x will remain unsupported by sift.

**Closed as completed by svent** 2015-10-25 18:28 UTC
