### ISSUE TITLE
mutiple options with --dirs doesn't work in Windows

### ISSUE THREAD

**Issue by KayLeung** [svent/sift#8] opened 2015-09-18 08:00 UTC
Not Working:
`sift --dirs core text` // Output: matching strings but skipped --dirs restriction.
`sift --dirs core -x js text` // Output: Nothing

Tested in `sift 0.3.2`
Tested in following shells:
- Windows Command Line
- Windows GIT Bash
- Powershell

**Comment by svent** [comment] 2015-09-19 23:22
I tried to reproduce this, but it in my tests it works as expected for me so far.
Could you provide some more details about the content and paths of the searched files and your expected output?

Please note that the option `--dirs` only restricts the directories sift will recurse into. It will (by default) still search the current directory and and all directories given via commandline.

**Comment by richrumble** [comment] 2015-10-01 16:46
I'm having trouble using wild card's for file names in windows
D:\sift.exe oct2014 *.csv
Error: cannot open file or directory: *.csv
If I use --dirs *.csv it will work but seems odd to use "directory" when dealing with files in the current directory I guess.

Also some odd behavior with -i and --dirs on windows (same search one with -i one without)
oct2014 is a valid (and proper case) string when it's found (second example) I've had to redact the data. If I capitalize the "o" (Oct2014) same output as -i below with or without -i, no match is expected because of case.

D:\sift.exe -i oct2014 --dirs *csv
Error: cannot process data from file '2015-09-24_12.file.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file '2015-09-28_09.file.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file '2015-09-29_01.file.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file '2015-09-30_11.file.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file '2015-10-01_10.file.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file 'diffs.csv': file contains very long lines (no newline in 262144 bytes)
Error: cannot process data from file 'db-2.csv': file contains very long lines (no newline in 262144 bytes)
-----------------vs---------------------- (redacted data)
D:\sift.exe oct2014 --dirs *csv
2015-09-22_11.file.csv:"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",xxxxxxxxxxxxxxxxx,"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",4,20050826204833.0x,20120627125227.0x,63739,,,,63739,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,x'xx37x960614201458x77x97x8x9xx4xx',,,,,,,,,,,,,,,,,,,,,,,,"xx=xxxx-xxxxx-xxx-xxxxx,xx=xxxxxx,xx=xxxxxxxxxxxxx,xx=xxxx,xx=xxxxx,xx=xxx",,,,20140626175218.0x;20140312132805.0x;20140304154747.0x;20140116141829.0x;16010714223649.0x,,,,,,,,,,,,,,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,xxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,x'58xx518xxxx9x642xx6x99x8332xx0582828574x260xxx119x1300508xx9xx86',1477,,,,,,,,,,,,,,,,,,,,,,,,,,

2015-09-22_11.file.csv:"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",xxxxxxxxxxxxxxxxx,"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",4,20050223125820.0x,20120627125205.0x,22091,,,,22091,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,x'11824xx81x76xx43x23768x971xxxx9x',,,,,,,,,,,,,,,,,,,,,,,,"xx=xxxx-xxxxx-xxx-xxxxx,xx=xxxxxx,xx=xxxxxxxxxxxxx,xx=xxxx,xx=xxxxx,xx=xxx",,,,20140626175216.0x;20140312132803.0x;20140304154745.0x;20140116141827.0x;16010714223649.0x,,,,,,,,,,,,,,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,xxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,x'885x92x827x7964xxxx62xxx5x06x3x20145833x7x83x9119xxx00x0591146xx',1434,,,,,,,,,,,,,,,,,,,,,,,,,,

2015-09-23_01.file.csv:"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",xxxxxxxxxxxxxxxxx,"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",4,20050826204833.0x,20120627125227.0x,63739,,,,63739,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,x'xx37x960614201458x77x97x8x9xx4xx',,,,,,,,,,,,,,,,,,,,,,,,"xx=xxxx-xxxxx-xxx-xxxxx,xx=xxxxxx,xx=xxxxxxxxxxxxx,xx=xxxx,xx=xxxxx,xx=xxx",,,,20140626175218.0x;20140312132805.0x;20140304154747.0x;20140116141829.0x;16010714223649.0x,,,,,,,,,,,,,,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,xxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,x'58xx518xxxx9x642xx6x99x8332xx0582828574x260xxx119x1300508xx9xx86',1477,,,,,,,,,,,,,,,,,,,,,,,,,,

2015-09-23_01.file.csv:"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",xxxxxxxxxxxxxxxxx,"xx=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,xx=xxxxxxxxxxxxxxx,xx=xxxxxxxxx,xx=xxxxxx,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",4,20050223125820.0x,20120627125205.0x,22091,,,,22091,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,x'11824xx81x76xx43x23768x971xxxx9x',,,,,,,,,,,,,,,,,,,,,,,,"xx=xxxx-xxxxx-xxx-xxxxx,xx=xxxxxx,xx=xxxxxxxxxxxxx,xx=xxxx,xx=xxxxx,xx=xxx",,,,20140626175216.0x;20140312132803.0x;20140304154745.0x;20140116141827.0x;16010714223649.0x,,,,,,,,,,,,,,xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,xxxx,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,x'885x92x827x7964xxxx62xxx5x06x3x20145833x7x83x9119xxx00x0591146xx',1434,,,,,,,,,,,,,,,,,,,,,,,,,,

**Comment by svent** [comment] 2015-10-01 22:23
Thanks for the detailed description. The problem seems to be that on windows the argument `*.csv` is directly given to sift and not resolved into the matching files (this is the case on unix based systems). I will create a fix for that in the next days.

The `-dirs` option does not really work as one might think in your example: `sift.exe oct2014 --dirs *csv` searches for oct2014 in the current directory and only recurses into directories matching *csv. If you execute `sift.exe oct2014` without any target files/dirs you should get the same result.

The ignore case difference looks really strange. Do you use the latest version of sift?

**Comment by richrumble** [comment] 2015-10-02 02:20
D:\sift.exe -V
sift 0.3.4

I've got a lot of funkiness with sift on windows, you can pipe data into it yes? I'm getting broken pipe messages.It's late need sleep, I'll try it again tomorrow and on more machines next time.

**Comment by svent** [comment] 2015-11-01 15:54
The initial problem should be solved for some time - I will close this issue for now.

**Closed as completed by svent** 2015-11-01 15:54 UTC
Labels: need-feedback
